services:
  mysql:
    env_file:
      - .env
    build:
      context: ./mysql
      dockerfile: database.Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE:${MYSQL_DATABASE}
        - MYSQL_USER:${MYSQL_USER}
        - MYSQL_PASSWORD:${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${MYSQL_PORT}:8128"
    volumes:
     - ./mysql/data/:/docker-entrypoint-initdb.d
